### ISSUE TITLE
Missing Function in Example

### ISSUE THREAD

**Issue by ic-twist** [iwanders/MFRC630#24]
Thanks for sharing this project.
I noticed that in the Arduino example code, there're references to function calls such as `mfrc630_iso14443a_REQA` that is not defined anywhere in the project. Could you please help me understand where those are defined?
I'm surprised that people can compile the example code... Am I missing something?

**Comment by iwanders** [comment]
Hey, I expect something is wrong with the includes / library usage.

The declaration is [here](https://github.com/iwanders/MFRC630/blob/577b0433a7dfae3fe3eba7a578d784982d90be69/mfrc630.h#L537), the definition is [here](https://github.com/iwanders/MFRC630/blob/577b0433a7dfae3fe3eba7a578d784982d90be69/mfrc630.c#L297-L299).

I expect it needs a bit of fiddling to get your toolchain to pick the files up?

**Comment by ic-twist** [comment]
I see - thanks for the pointer. I did a search in the repo but the function definition didn't show up and that got me confused. Thanks again.

**Comment by iwanders** [comment]
All good, I hope you get it working :+1:
