### ISSUE TITLE
Selection of  setup registers

### ISSUE THREAD

**Issue by VladiAron** [iwanders/MFRC630#5]
https://github.com/iwanders/MFRC630/blob/5768981807e9f8b0eb2b4c2f00ff3a334c620472/examples/arduino_example/arduino_example.ino#L158

Hello! Can you help me? I have board with MFRC630 and custom antenna. And I don`t understand where is problem antenna? MFRC630 setup? or may be smth else?  It will be realy awesome if you can explain me how did you chose values for this registers, by what reasons I mean.

**Comment by iwanders** [comment]
If your custom board came with example code, just use the setup values from the example code. If it didn't look in the [datasheet](https://www.nxp.com/docs/en/data-sheet/MFRC630.pdf) at each of the setup registers, what they mean and how they should be configured for your hardware. Obviously do the usual tests first, check whether voltages are correct, check if the SPI bus works... Then move on to the register settings and setup.
