### ISSUE TITLE
IS015693 anticollision code for CLRC6330

### ISSUE THREAD

**Issue by nsrinivas37** [iwanders/MFRC630#9]
Hi @iwanders could you provide the sample code for ISO15693 tags detection with anticollision

**Comment by iwanders** [comment]
Hi @nsrinivas37 , I cannot, because I have not worked on ISO15693 myself.

Other people have been discussing ISO 15693 under issue #4. Please read that thread and comment there, I've reopened that issue for visibility. I'm closing this one to ensure we keep the discussion in one issue.
